# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-03 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0003_auto_20190303_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticfile',
            name='file_name',
            field=models.CharField(default='bootstrap.min.css', max_length=100, unique=True, verbose_name='File name'),
            preserve_default=False,
        ),
    ]
