# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-03 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0004_staticfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefile',
            name='static_files',
            field=models.ManyToManyField(to='landings.StaticFile', verbose_name='Used static files'),
        ),
    ]
