# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-03 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0005_templatefile_static_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='images_count',
            field=models.IntegerField(default=5, verbose_name='Images count'),
        ),
    ]
