# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-03 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0006_landing_images_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingimage',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Image position'),
        ),
    ]
