# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0008_auto_20190304_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingimage',
            name='alternative_text',
        ),
    ]
